linters:
  fast: false
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - dupl
    - exhaustive
    - exportloopref
    - gocritic
    - goerr113
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - lll
    - misspell
    - nolintlint
    - prealloc
    - exportloopref
    - unconvert
    - unparam

issues:
  exclude-use-default: true
  max-issues-per-linter: 0

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 5
