project_name: amfora

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: netbsd
        goarch: arm
      - goos: netbsd
        goarch: arm64
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - format: binary
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit

milestones:
  - close: true

changelog:
  skip: true
