language: go

go:
  #- "1.11"  # Debian Stable golang version, fails - see below
  #- "1.12"  # Also fails due to progressbar Millisecond requirement
  - "1.13"
  - "1.14"
  - "1.15"

os:
  - linux
  - osx
  - windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi

script:
  - go test -race ./...
  - make

env:
  GO111MODULE=on

cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod

# TODO: GitHub Releases deploy

notifications:
  email:
    on_success: never
    on_failure: always
