.Dd $Mdocdate$
.Dt AMFORA 1
.Os
.Sh NAME
.Nm amfora
.Nd fancy terminal gemini browser
.Sh SYNOPSIS
.Nm amfora
.Ar url
.Sh DESCRIPTION
The
.Nm
is a gemini client in your terminal.
The documentation is maintained at
.Lk https://github.com/makeworld-the-better-one/amfora/wiki
.Sh KEY BINDINGS
.It ?
Open help menu
.It q
Exit amfora
.\" .Sh EXAMPLES
.\" .Sh ERRORS
.\" .Sh ENVIRONMENT
.Sh STANDARDS
.Lk https://gemini.circumlunar.space/docs/specification.gmi
.Sh HISTORY
.Nm
development started in June, 2020.
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
