[theme]

# atelier forest light

bg =                        "#f1efee"
fg =                        "#68615e"
tab_num =                   "#68615e"
tab_divider =               "#e6e2e0"
bottombar_label =           "#3d97b8"
bottombar_text =            "#68615e"
bottombar_bg =              "#f1efee"
scrollbar =                 "#68615e"

hdg_1 =                     "#f22c40"
hdg_2 =                     "#7b9726"
hdg_3 =                     "#c33ff3"
amfora_link =               "#407ee7"
foreign_link =              "#f22c40"
link_number =               "#68615e"
regular_text =              "#68615e"
quote_text =                "#68615e"
preformatted_text =         "#68615e"
list_text =                 "#68615e"

btn_bg =                    "#407ee7"
btn_text =                  "#f1efee"

dl_choice_modal_bg =        "#e6e2e0"
dl_choice_modal_text =      "#68615e"
dl_modal_bg =               "#e6e2e0"
dl_modal_text =             "#68615e"
info_modal_bg =             "#e6e2e0"
info_modal_text =           "#68615e"
error_modal_bg =            "#e6e2e0"
error_modal_text =          "#f22c40"
yesno_modal_bg =            "#e6e2e0"
yesno_modal_text =          "#68615e"
tofu_modal_bg =             "#e6e2e0"
tofu_modal_text =           "#68615e"
subscription_modal_bg =     "#e6e2e0"
subscription_modal_text =   "#68615e"

input_modal_bg =            "#e6e2e0"
input_modal_text =          "#68615e"
input_modal_field_bg =      "#f1efee"
input_modal_field_text =    "#68615e"

bkmk_modal_bg =             "#e6e2e0"
bkmk_modal_text =           "#68615e"
bkmk_modal_label =          "#3d97b8"
bkmk_modal_field_bg =       "#f1efee"
bkmk_modal_field_text =     "#68615e"
