[theme]
bg = "#282a36"
tab_num = "#bd93f9"
tab_divider = "#f8f8f2"
bottombar_label = "#bd93f9"
bottombar_text = "#8be9fd"
bottombar_bg = "#44475a"
scrollbar = "#44475a"

hdg_1 = "#bd93f9"
hdg_2 = "#bd93f9"
hdg_3 = "#bd93f9"
amfora_link = "#ff79c6"
foreign_link = "#ffb86c"
link_number = "#8be9fd"
regular_text = "#f8f8f2"
quote_text = "#f1fa8c"
preformatted_text = "#ffb86c"
list_text = "#f8f8f2"

btn_bg = "#44475a"
btn_text = "#f8f8f2"

dl_choice_modal_bg = "#6272a4"
dl_choice_modal_text = "#f8f8f2"
dl_modal_bg = "#6272a4"
dl_modal_text = "#f8f8f2"
info_modal_bg = "#6272a4"
info_modal_text = "#f8f8f2"
error_modal_bg = "#ff5555"
error_modal_text = "#f8f8f2"
yesno_modal_bg = "#6272a4"
yesno_modal_text = "#f8f8f2"
tofu_modal_bg = "#6272a4"
tofu_modal_text = "#f8f8f2"
subscription_modal_bg = "#6272a4"
subscription_modal_text = "#f8f8f2"

input_modal_bg = "#6272a4"
input_modal_text = "#f8f8f2"
input_modal_field_bg = "#44475a"
input_modal_field_text = "#f8f8f2"

bkmk_modal_bg = "#6272a4"
bkmk_modal_text = "#f8f8f2"
bkmk_modal_label = "#f8f8f2"
bkmk_modal_field_bg = "#44475a"
bkmk_modal_field_text = "#f8f8f2"
