[theme]
# This section is for changing the COLORS used in Amfora.
# These colors only apply if 'color' is enabled above.
# Colors can be set using a W3C color name, or a hex value such as "#ffffff".

# Note that not all colors will work on terminals that do not have truecolor support.
# If you want to stick to the standard 16 or 256 colors, you can get
# a list of those here: https://jonasjacek.github.io/colors/
# DO NOT use the names from that site, just the hex codes.

# Definitions:
#   bg = background
#   fg = foreground
#   dl = download
#   btn = button
#   hdg = heading
#   bkmk = bookmark
#   modal = a popup window/box in the middle of the screen

# EXAMPLES:
# hdg_1 = "green"
# hdg_2 = "#5f0000"

# Available keys to set:

# bg: background for pages, tab row, app in general
# tab_num: The number/highlight of the tabs at the top
# tab_divider: The color of the divider character between tab numbers: |
# bottombar_label: The color of the prompt that appears when you press space
# bottombar_text: The color of the text you type
# bottombar_bg

bg = 			"#282a36"
fg = 			"#f8f8f2"
tab_num = 		"#50fa7b"
tab_divider = 		"#f8f8f2"
bottombar_bg = 		"#282a36"
bottombar_text = 	"#f8f8f2"
bottombar_label = 	"#9aedfe"

# hdg_1
# hdg_2
# hdg_3
# amfora_link: A link that Amfora supports viewing. For now this is only gemini://
# foreign_link: HTTP(S), Gopher, etc
# link_number: The silver number that appears to the left of a link
# regular_text: Normal gemini text, and plaintext documents
# quote_text
# preformatted_text
# list_text

hdg_1 =			"#5af78e"
hdg_2 =			"#9aedfe"
hdg_3 =			"#caa9fa"
amfora_link =		"#f4f99d"
foreign_link =		"#d4d989"
link_number =		"#ff5555"
regular_text = 		"#f8f8f2"
quote_text =		"#E6E6E6"
preformatted_text =	"#f8f8f2"
list_text =		"#f8f8f2"

# btn_bg: The bg color for all modal buttons
# btn_text: The text color for all modal buttons

btn_bg = 		"#bfbfbf"
btn_text =		"#4d4d4d"

dl_choice_modal_bg =	"#282a36"
dl_choice_modal_text =	"#f8f8f2"
dl_modal_bg =		"#282a36"
dl_modal_text =		"#f8f8f2"
info_modal_bg =		"#282a36"
info_modal_text =	"#f8f8f2"
error_modal_bg =	"#282a36"
error_modal_text =	"#ff5555"
yesno_modal_bg =	"#282a36"
yesno_modal_text =	"#f1fa8c"
tofu_modal_bg =		"#282a36"
tofu_modal_text =	"#f8f8f2"

# input_modal_bg
# input_modal_text
# input_modal_field_bg: The bg of the input field, where you type the text
# input_modal_field_text: The color of the text you type

input_modal_bg =	"#282a36"
input_modal_text =	"#f8f8f2"
input_modal_field_bg =	"#4d4d4d"
input_modal_field_text ="#f8f8f2"

# bkmk_modal_bg
# bkmk_modal_text
# bkmk_modal_label
# bkmk_modal_field_bg
# bkmk_modal_field_text

bkmk_modal_bg =		"#282a36"
bkmk_modal_text =	"#f8f8f2"
bkmk_modal_label =	"#f8f8f2"
bkmk_modal_field_bg =	"#000000"
bkmk_modal_field_text = "#f8f8f2"

subscription_modal_bg =	"#282a36"
subscription_modal_text = "#f8f8f2"
