[theme]
bg = "#ffffff"
tab_num = "#000000"
tab_divider = "#000000"
bottombar_label = "#ffffff"
bottombar_text = "#ffffff"
bottombar_bg = "#000000"

hdg_1 = "#000000"
hdg_2 = "#000000"
hdg_3 = "#000000"
amfora_link = "#000000"
foreign_link = "#7f7f7f"
link_number = "#000000"
regular_text = "#000000"
quote_text = "#000000"
preformatted_text = "#000000"
list_text = "#000000"

btn_bg = "#efefef"
btn_text = "#000000"

dl_choice_modal_bg = "#efefef"
dl_choice_modal_text = "#000000"
dl_modal_bg = "#efefef"
dl_modal_text = "#000000"
info_modal_bg = "#efefef"
info_modal_text = "#000000"
error_modal_bg = "#efefef"
error_modal_text = "#000000"
yesno_modal_bg = "#efefef"
yesno_modal_text = "#000000"
tofu_modal_bg = "#efefef"
tofu_modal_text = "#000000"
subscription_modal_bg = "#efefef"
subscription_modal_text = "#000000"

input_modal_bg = "#efefef"
input_modal_text = "#000000"
input_modal_field_bg = "#ffffff"
input_modal_field_text = "#000000"

bkmk_modal_bg = "#efefef"
bkmk_modal_text = "#000000"
bkmk_modal_label = "#000000"
bkmk_modal_field_bg = "#ffffff"
bkmk_modal_field_text = "#000000"
