## name: Rosé Pine
## upstream: https://github.com/rose-pine/amfora/blob/main/themes/rose-pine-dawn.toml
## description: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

bg = "#faf4ed"
tab_num = "#907aa9"
tab_divider = "#dfdad9"
bottombar_label = "#907aa9"
bottombar_text = "#575279"
bottombar_bg = "#fffaf3"
scrollbar = "#f4ede8"
hdg_1 = "#907aa9"
hdg_2 = "#56949f"
hdg_3 = "#d7827e"
amfora_link = "#ea9d34"
foreign_link = "#797593"
link_number = "#9893a5"
regular_text = "#575279"
quote_text = "#575279"
preformatted_text = "#575279"
list_text = "#575279"
btn_bg = "#286983"
btn_text = "#575279"
dl_choice_modal_bg = "#fffaf3"
dl_choice_modal_text = "#575279"
dl_modal_bg = "#fffaf3"
dl_modal_text = "#575279"
info_modal_bg = "#fffaf3"
info_modal_text = "#575279"
error_modal_bg = "#fffaf3"
error_modal_text = "#b4637a"
yesno_modal_bg = "#fffaf3"
yesno_modal_text = "#575279"
tofu_modal_bg = "#fffaf3"
tofu_modal_text = "#575279"
subscription_modal_bg = "#fffaf3"
subscription_modal_text = "#575279"
input_modal_bg = "#fffaf3"
input_modal_text = "#575279"
input_modal_field_bg = "#f2e9e1"
input_modal_field_text = "#575279"
bkmk_modal_bg = "#fffaf3"
bkmk_modal_text = "#575279"
bkmk_modal_label = "#907aa9"
bkmk_modal_field_bg = "#f2e9e1"
bkmk_modal_field_text = "#575279"
