#[theme]
# This section is for changing the COLORS used in Amfora.
# These colors only apply if 'color' is enabled above.
# Colors can be set using a W3C color name, or a hex value such as "#ffffff".

# Note that not all colors will work on terminals that do not have truecolor support.
# If you want to stick to the standard 16 or 256 colors, you can get
# a list of those here: https://jonasjacek.github.io/colors/
# DO NOT use the names from that site, just the hex codes.

# Definitions:
#   bg = background
#   fg = foreground
#   dl = download
#   btn = button
#   hdg = heading
#   bkmk = bookmark
#   modal = a popup window/box in the middle of the screen

# EXAMPLES:
# hdg_1 = "green"
# hdg_2 = "#5f0000"

# Available keys to set:

# bg: background for pages, tab row, app in general
bg = "#c7fcd6"
# tab_num: The number/highlight of the tabs at the top
tab_num = "#f49ab9"
# tab_divider: The color of the divider character between tab numbers: |
tab_divider = "#117bf4"
# bottombar_label: The color of the prompt that appears when you press space
bottomrbar_label = "#e9f411"
# bottombar_text: The color of the text you type
bottombar_text = "#040405"
# bottombar_bg
bottombar_bg = "#1fbde0"

hdg_1 = "#a369ef" 
hdg_2 = "#ef69ba"
hdg_3 = "#f4295f"
# amfora_link: A link that Amfora supports viewing. For now this is only gemini://
amfora_link = "#A020F0"
# foreign_link: HTTP(S), Gopher, etc
foreign_link = "#808080"
# link_number: The silver number that appears to the left of a link
link_number = "#2662e2"
# regular_text: Normal gemini text, and plaintext documents
regular_text = "#04000c"
# quote_text
quote_text = "#666699"
# preformatted_text
preformatted_text = "#ff1493"
# list_text
list_text = "#04000c"

# btn_bg: The bg color for all modal buttons
# btn_text: The text color for all modal buttons

# dl_choice_modal_bg
# dl_choice_modal_text
# dl_modal_bg
# dl_modal_text
# info_modal_bg
# info_modal_text
# error_modal_bg
# error_modal_text
# yesno_modal_bg
# yesno_modal_text
# tofu_modal_bg
# tofu_modal_text

# input_modal_bg
# input_modal_text
# input_modal_field_bg: The bg of the input field, where you type the text
# input_modal_field_text: The color of the text you type

# bkmk_modal_bg
# bkmk_modal_text
# bkmk_modal_label
# bkmk_modal_field_bg
# bkmk_modal_field_text
