on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula-name: amfora
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
